// Auto-generated from S&P 500 GICS data + ETF/extra stock classifications
// Total entries: 989
export const SECTOR_MAP: Record<string, { sector: string; subsector: string }> = {
  "A": { sector: "Health Care", subsector: "Life Sciences Tools & Services" },
  "AAOI": { sector: "Information Technology", subsector: "Optical Components" },
  "AAPL": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "ABBV": { sector: "Health Care", subsector: "Biotechnology" },
  "ABNB": { sector: "Consumer Discretionary", subsector: "Hotels, Resorts & Cruise Lines" },
  "ABT": { sector: "Health Care", subsector: "Health Care Equipment" },
  "ACGL": { sector: "Financials", subsector: "Property & Casualty Insurance" },
  "ACHR": { sector: "Industrials", subsector: "Defense & Space" },
  "ACN": { sector: "Information Technology", subsector: "IT Consulting & Other Services" },
  "ADBE": { sector: "Information Technology", subsector: "Application Software" },
  "ADI": { sector: "Information Technology", subsector: "Semiconductors" },
  "ADM": { sector: "Consumer Staples", subsector: "Agricultural Products & Services" },
  "ADP": { sector: "Industrials", subsector: "Human Resource & Employment Services" },
  "ADSK": { sector: "Information Technology", subsector: "Application Software" },
  "AEE": { sector: "Utilities", subsector: "Multi-Utilities" },
  "AEHR": { sector: "Information Technology", subsector: "Semiconductor Test" },
  "AEP": { sector: "Utilities", subsector: "Electric Utilities" },
  "AER": { sector: "Industrials", subsector: "Aircraft Leasing" },
  "AES": { sector: "Utilities", subsector: "Independent Power Producers & Energy Traders" },
  "AFL": { sector: "Financials", subsector: "Life & Health Insurance" },
  "AFRM": { sector: "Financials", subsector: "Fintech" },
  "AGG": { sector: "Fixed Income", subsector: "Bond ETF" },
  "AI": { sector: "Information Technology", subsector: "AI Platform" },
  "AIG": { sector: "Financials", subsector: "Multi-line Insurance" },
  "AIZ": { sector: "Financials", subsector: "Multi-line Insurance" },
  "AJG": { sector: "Financials", subsector: "Insurance Brokers" },
  "AKAM": { sector: "Information Technology", subsector: "Internet Services & Infrastructure" },
  "ALAB": { sector: "Information Technology", subsector: "Semiconductors" },
  "ALB": { sector: "Materials", subsector: "Specialty Chemicals" },
  "ALGN": { sector: "Health Care", subsector: "Health Care Supplies" },
  "ALK": { sector: "Industrials", subsector: "Airlines" },
  "ALL": { sector: "Financials", subsector: "Property & Casualty Insurance" },
  "ALLE": { sector: "Industrials", subsector: "Building Products" },
  "ALRIB": { sector: "Information Technology", subsector: "Semiconductor Materials & Equipment" },
  "AMAT": { sector: "Information Technology", subsector: "Semiconductor Materials & Equipment" },
  "AMBR": { sector: "Financials", subsector: "Fintech" },
  "AMC": { sector: "Consumer Discretionary", subsector: "Entertainment" },
  "AMCR": { sector: "Materials", subsector: "Paper & Plastic Packaging Products & Materials" },
  "AMD": { sector: "Information Technology", subsector: "Semiconductors" },
  "AME": { sector: "Industrials", subsector: "Electrical Components & Equipment" },
  "AMGN": { sector: "Health Care", subsector: "Biotechnology" },
  "AMKR": { sector: "Information Technology", subsector: "Semiconductors" },
  "AMP": { sector: "Financials", subsector: "Asset Management & Custody Banks" },
  "AMPG": { sector: "Information Technology", subsector: "Semiconductors" },
  "AMSC": { sector: "Industrials", subsector: "Power Electronics" },
  "AMT": { sector: "Real Estate", subsector: "Telecom Tower REITs" },
  "AMZN": { sector: "Consumer Discretionary", subsector: "Broadline Retail" },
  "ANET": { sector: "Information Technology", subsector: "Communications Equipment" },
  "ANF": { sector: "Consumer Discretionary", subsector: "Apparel Retail" },
  "ANSS": { sector: "Information Technology", subsector: "Software" },
  "AON": { sector: "Financials", subsector: "Insurance Brokers" },
  "AOS": { sector: "Industrials", subsector: "Building Products" },
  "AOSL": { sector: "Information Technology", subsector: "Semiconductors" },
  "APA": { sector: "Energy", subsector: "Oil & Gas Exploration & Production" },
  "APD": { sector: "Materials", subsector: "Industrial Gases" },
  "APH": { sector: "Information Technology", subsector: "Electronic Components" },
  "APLD": { sector: "Digital Assets", subsector: "Crypto Mining" },
  "APO": { sector: "Financials", subsector: "Asset Management & Custody Banks" },
  "APP": { sector: "Information Technology", subsector: "Application Software" },
  "APTV": { sector: "Consumer Discretionary", subsector: "Automotive Parts & Equipment" },
  "ARE": { sector: "Real Estate", subsector: "Office REITs" },
  "ARES": { sector: "Financials", subsector: "Asset Management & Custody Banks" },
  "ARKB": { sector: "Digital Assets", subsector: "Bitcoin ETF" },
  "ARKF": { sector: "Innovation", subsector: "Thematic ETF" },
  "ARKG": { sector: "Innovation", subsector: "Thematic ETF" },
  "ARKK": { sector: "Innovation", subsector: "Thematic ETF" },
  "ARKQ": { sector: "Innovation", subsector: "Thematic ETF" },
  "ARKW": { sector: "Innovation", subsector: "Thematic ETF" },
  "ARM": { sector: "Information Technology", subsector: "Semiconductor IP" },
  "ASHR": { sector: "Broad Market", subsector: "Equity ETF" },
  "ASML": { sector: "Information Technology", subsector: "Semiconductors" },
  "ASTS": { sector: "Communication Services", subsector: "Satellite Broadband" },
  "ASX": { sector: "Information Technology", subsector: "Semiconductors" },
  "ASYS": { sector: "Information Technology", subsector: "Semiconductor Equipment" },
  "ATO": { sector: "Utilities", subsector: "Gas Utilities" },
  "AVB": { sector: "Real Estate", subsector: "Multi-Family Residential REITs" },
  "AVGO": { sector: "Information Technology", subsector: "Semiconductors" },
  "AVY": { sector: "Materials", subsector: "Paper & Plastic Packaging Products & Materials" },
  "AWK": { sector: "Utilities", subsector: "Water Utilities" },
  "AXON": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "AXP": { sector: "Financials", subsector: "Consumer Finance" },
  "AXSM": { sector: "Health Care", subsector: "Biotech" },
  "AXTI": { sector: "Information Technology", subsector: "Semiconductors" },
  "AZO": { sector: "Consumer Discretionary", subsector: "Automotive Retail" },
  "BA": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "BAC": { sector: "Financials", subsector: "Diversified Banks" },
  "BALL": { sector: "Materials", subsector: "Metal, Glass & Plastic Containers" },
  "BATT": { sector: "Materials", subsector: "Thematic ETF" },
  "BAX": { sector: "Health Care", subsector: "Health Care Equipment" },
  "BB": { sector: "Information Technology", subsector: "Cybersecurity" },
  "BBAI": { sector: "Information Technology", subsector: "AI Analytics" },
  "BBWI": { sector: "Consumer Discretionary", subsector: "Specialty Retail" },
  "BBY": { sector: "Consumer Discretionary", subsector: "Computer & Electronics Retail" },
  "BDC": { sector: "Industrials", subsector: "Cable Manufacturing" },
  "BDX": { sector: "Health Care", subsector: "Health Care Equipment" },
  "BEN": { sector: "Financials", subsector: "Asset Management & Custody Banks" },
  "BF.B": { sector: "Consumer Staples", subsector: "Distillers & Vintners" },
  "BG": { sector: "Consumer Staples", subsector: "Agricultural Products & Services" },
  "BIIB": { sector: "Health Care", subsector: "Biotechnology" },
  "BIL": { sector: "Fixed Income", subsector: "Bond ETF" },
  "BITB": { sector: "Digital Assets", subsector: "Bitcoin ETF" },
  "BITO": { sector: "Digital Assets", subsector: "Bitcoin Futures ETF" },
  "BITX": { sector: "Fixed Income", subsector: "Leveraged ETF" },
  "BK": { sector: "Financials", subsector: "Custody Banking" },
  "BKF": { sector: "Broad Market", subsector: "Equity ETF" },
  "BKKT": { sector: "Financials", subsector: "Crypto Exchange" },
  "BKLN": { sector: "Fixed Income", subsector: "Bond ETF" },
  "BKNG": { sector: "Consumer Discretionary", subsector: "Hotels, Resorts & Cruise Lines" },
  "BKR": { sector: "Energy", subsector: "Oil & Gas Equipment & Services" },
  "BLDR": { sector: "Industrials", subsector: "Building Products" },
  "BLK": { sector: "Financials", subsector: "Asset Management & Custody Banks" },
  "BMY": { sector: "Health Care", subsector: "Pharmaceuticals" },
  "BND": { sector: "Fixed Income", subsector: "Bond ETF" },
  "BNO": { sector: "Commodities", subsector: "Commodity ETF" },
  "BNY": { sector: "Financials", subsector: "Asset Management & Custody Banks" },
  "BOTZ": { sector: "Information Technology", subsector: "Thematic ETF" },
  "BR": { sector: "Industrials", subsector: "Data Processing & Outsourced Services" },
  "BRK": { sector: "Financials", subsector: "Conglomerate" },
  "BRK.B": { sector: "Financials", subsector: "Multi-Sector Holdings" },
  "BRK_B": { sector: "Financials", subsector: "Conglomerate" },
  "BRO": { sector: "Financials", subsector: "Insurance Brokers" },
  "BROS": { sector: "Consumer Discretionary", subsector: "Restaurants" },
  "BSX": { sector: "Health Care", subsector: "Health Care Equipment" },
  "BTBT": { sector: "Digital Assets", subsector: "Crypto Mining" },
  "BTGO": { sector: "Financials", subsector: "Crypto Exchange" },
  "BWA": { sector: "Consumer Discretionary", subsector: "Auto Parts" },
  "BWXT": { sector: "Energy", subsector: "Nuclear Services" },
  "BX": { sector: "Financials", subsector: "Asset Management & Custody Banks" },
  "BXP": { sector: "Real Estate", subsector: "Office REITs" },
  "C": { sector: "Financials", subsector: "Diversified Banks" },
  "CAG": { sector: "Consumer Staples", subsector: "Packaged Foods & Meats" },
  "CAH": { sector: "Health Care", subsector: "Health Care Distributors" },
  "CAN": { sector: "Information Technology", subsector: "Crypto Mining Equipment" },
  "CARR": { sector: "Industrials", subsector: "Building Products" },
  "CASY": { sector: "Consumer Staples", subsector: "Food Retail" },
  "CAT": { sector: "Industrials", subsector: "Construction Machinery & Heavy Transportation Equipment" },
  "CAVA": { sector: "Consumer Discretionary", subsector: "Restaurants" },
  "CB": { sector: "Financials", subsector: "Property & Casualty Insurance" },
  "CBOE": { sector: "Financials", subsector: "Financial Exchanges & Data" },
  "CBRE": { sector: "Real Estate", subsector: "Real Estate Services" },
  "CCI": { sector: "Real Estate", subsector: "Telecom Tower REITs" },
  "CCJ": { sector: "Energy", subsector: "Uranium Mining" },
  "CCL": { sector: "Consumer Discretionary", subsector: "Hotels, Resorts & Cruise Lines" },
  "CDNS": { sector: "Information Technology", subsector: "Application Software" },
  "CDW": { sector: "Information Technology", subsector: "Technology Distributors" },
  "CE": { sector: "Materials", subsector: "Specialty Chemicals" },
  "CEG": { sector: "Utilities", subsector: "Electric Utilities" },
  "CELH": { sector: "Consumer Staples", subsector: "Beverages" },
  "CF": { sector: "Materials", subsector: "Fertilizers & Agricultural Chemicals" },
  "CFG": { sector: "Financials", subsector: "Regional Banks" },
  "CHD": { sector: "Consumer Staples", subsector: "Household Products" },
  "CHRW": { sector: "Industrials", subsector: "Air Freight & Logistics" },
  "CHTR": { sector: "Communication Services", subsector: "Cable & Satellite" },
  "CI": { sector: "Health Care", subsector: "Health Care Services" },
  "CIEN": { sector: "Information Technology", subsector: "Communications Equipment" },
  "CIFR": { sector: "Digital Assets", subsector: "Crypto Mining" },
  "CINF": { sector: "Financials", subsector: "Property & Casualty Insurance" },
  "CL": { sector: "Consumer Staples", subsector: "Household Products" },
  "CLOU": { sector: "Information Technology", subsector: "Thematic ETF" },
  "CLS": { sector: "Information Technology", subsector: "EMS" },
  "CLSK": { sector: "Digital Assets", subsector: "Crypto Mining" },
  "CLX": { sector: "Consumer Staples", subsector: "Household Products" },
  "CMA": { sector: "Financials", subsector: "Regional Banks" },
  "CMCSA": { sector: "Communication Services", subsector: "Cable & Satellite" },
  "CME": { sector: "Financials", subsector: "Financial Exchanges & Data" },
  "CMG": { sector: "Consumer Discretionary", subsector: "Restaurants" },
  "CMI": { sector: "Industrials", subsector: "Construction Machinery & Heavy Transportation Equipment" },
  "CMS": { sector: "Utilities", subsector: "Multi-Utilities" },
  "CNC": { sector: "Health Care", subsector: "Managed Health Care" },
  "CNP": { sector: "Utilities", subsector: "Multi-Utilities" },
  "COF": { sector: "Financials", subsector: "Consumer Finance" },
  "COHR": { sector: "Information Technology", subsector: "Electronic Components" },
  "COIN": { sector: "Financials", subsector: "Financial Exchanges & Data" },
  "COO": { sector: "Health Care", subsector: "Health Care Supplies" },
  "COP": { sector: "Energy", subsector: "Oil & Gas Exploration & Production" },
  "COR": { sector: "Health Care", subsector: "Health Care Distributors" },
  "CORZ": { sector: "Digital Assets", subsector: "Crypto Mining" },
  "COST": { sector: "Consumer Staples", subsector: "Consumer Staples Merchandise Retail" },
  "COUR": { sector: "Information Technology", subsector: "EdTech" },
  "CPAY": { sector: "Financials", subsector: "Transaction & Payment Processing Services" },
  "CPB": { sector: "Consumer Staples", subsector: "Packaged Foods & Meats" },
  "CPRT": { sector: "Industrials", subsector: "Diversified Support Services" },
  "CPT": { sector: "Real Estate", subsector: "Multi-Family Residential REITs" },
  "CRH": { sector: "Materials", subsector: "Construction Materials" },
  "CRL": { sector: "Health Care", subsector: "Life Sciences Tools & Services" },
  "CRM": { sector: "Information Technology", subsector: "Application Software" },
  "CRSP": { sector: "Health Care", subsector: "Biotech" },
  "CRWD": { sector: "Information Technology", subsector: "Systems Software" },
  "CRWV": { sector: "Financials", subsector: "Fintech" },
  "CSCO": { sector: "Information Technology", subsector: "Communications Equipment" },
  "CSGP": { sector: "Real Estate", subsector: "Real Estate Services" },
  "CSX": { sector: "Industrials", subsector: "Rail Transportation" },
  "CTAS": { sector: "Industrials", subsector: "Diversified Support Services" },
  "CTLT": { sector: "Health Care", subsector: "Pharma Services" },
  "CTRA": { sector: "Energy", subsector: "E&P" },
  "CTSH": { sector: "Information Technology", subsector: "IT Consulting & Other Services" },
  "CTVA": { sector: "Materials", subsector: "Fertilizers & Agricultural Chemicals" },
  "CVNA": { sector: "Consumer Discretionary", subsector: "Automotive Retail" },
  "CVS": { sector: "Health Care", subsector: "Health Care Services" },
  "CVX": { sector: "Energy", subsector: "Integrated Oil & Gas" },
  "CZR": { sector: "Consumer Discretionary", subsector: "Casinos" },
  "D": { sector: "Utilities", subsector: "Multi-Utilities" },
  "DAL": { sector: "Industrials", subsector: "Passenger Airlines" },
  "DASH": { sector: "Consumer Discretionary", subsector: "Specialized Consumer Services" },
  "DAX": { sector: "Broad Market", subsector: "Equity ETF" },
  "DD": { sector: "Materials", subsector: "Specialty Chemicals" },
  "DDOG": { sector: "Information Technology", subsector: "Application Software" },
  "DE": { sector: "Industrials", subsector: "Agricultural & Farm Machinery" },
  "DECK": { sector: "Consumer Discretionary", subsector: "Footwear" },
  "DELL": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "DG": { sector: "Consumer Staples", subsector: "Consumer Staples Merchandise Retail" },
  "DGX": { sector: "Health Care", subsector: "Health Care Services" },
  "DHI": { sector: "Consumer Discretionary", subsector: "Homebuilding" },
  "DHR": { sector: "Health Care", subsector: "Life Sciences Tools & Services" },
  "DIA": { sector: "Broad Market", subsector: "Equity ETF" },
  "DIS": { sector: "Communication Services", subsector: "Movies & Entertainment" },
  "DJP": { sector: "Commodities", subsector: "Commodity ETF" },
  "DJT": { sector: "Communication Services", subsector: "Social Media" },
  "DKNG": { sector: "Consumer Discretionary", subsector: "Gambling" },
  "DLR": { sector: "Real Estate", subsector: "Data Center REITs" },
  "DLTR": { sector: "Consumer Staples", subsector: "Consumer Staples Merchandise Retail" },
  "DNN": { sector: "Energy", subsector: "Uranium Mining" },
  "DOC": { sector: "Real Estate", subsector: "Health Care REITs" },
  "DOV": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "DOW": { sector: "Materials", subsector: "Commodity Chemicals" },
  "DPZ": { sector: "Consumer Discretionary", subsector: "Restaurants" },
  "DRI": { sector: "Consumer Discretionary", subsector: "Restaurants" },
  "DSL": { sector: "Fixed Income", subsector: "Closed-End Fund" },
  "DTE": { sector: "Utilities", subsector: "Multi-Utilities" },
  "DUK": { sector: "Utilities", subsector: "Electric Utilities" },
  "DUOL": { sector: "Information Technology", subsector: "EdTech" },
  "DVA": { sector: "Health Care", subsector: "Health Care Services" },
  "DVN": { sector: "Energy", subsector: "Oil & Gas Exploration & Production" },
  "DVY": { sector: "Broad Market", subsector: "Dividend ETF" },
  "DXCM": { sector: "Health Care", subsector: "Health Care Equipment" },
  "EA": { sector: "Communication Services", subsector: "Interactive Home Entertainment" },
  "EBAY": { sector: "Consumer Discretionary", subsector: "Broadline Retail" },
  "ECL": { sector: "Materials", subsector: "Specialty Chemicals" },
  "ED": { sector: "Utilities", subsector: "Multi-Utilities" },
  "EFA": { sector: "Broad Market", subsector: "Equity ETF" },
  "EFX": { sector: "Industrials", subsector: "Research & Consulting Services" },
  "EG": { sector: "Financials", subsector: "Reinsurance" },
  "EIX": { sector: "Utilities", subsector: "Electric Utilities" },
  "EL": { sector: "Consumer Staples", subsector: "Personal Care Products" },
  "ELF": { sector: "Consumer Staples", subsector: "Beauty" },
  "ELV": { sector: "Health Care", subsector: "Managed Health Care" },
  "EMB": { sector: "Fixed Income", subsector: "Bond ETF" },
  "EME": { sector: "Industrials", subsector: "Construction & Engineering" },
  "EMN": { sector: "Materials", subsector: "Chemicals" },
  "EMR": { sector: "Industrials", subsector: "Electrical Components & Equipment" },
  "ENPH": { sector: "Information Technology", subsector: "Solar Equipment" },
  "ENTG": { sector: "Information Technology", subsector: "Semiconductors" },
  "EOG": { sector: "Energy", subsector: "Oil & Gas Exploration & Production" },
  "EOSE": { sector: "Industrials", subsector: "Energy Storage" },
  "EPAM": { sector: "Information Technology", subsector: "IT Services" },
  "EPP": { sector: "Broad Market", subsector: "Equity ETF" },
  "EQIX": { sector: "Real Estate", subsector: "Data Center REITs" },
  "EQR": { sector: "Real Estate", subsector: "Multi-Family Residential REITs" },
  "EQT": { sector: "Energy", subsector: "Oil & Gas Exploration & Production" },
  "ERIE": { sector: "Financials", subsector: "Insurance Brokers" },
  "ERTH": { sector: "Information Technology", subsector: "Thematic ETF" },
  "ES": { sector: "Utilities", subsector: "Electric Utilities" },
  "ESPO": { sector: "Communication Services", subsector: "Thematic ETF" },
  "ESS": { sector: "Real Estate", subsector: "Multi-Family Residential REITs" },
  "ETHU": { sector: "Digital Assets", subsector: "Ethereum ETF" },
  "ETN": { sector: "Industrials", subsector: "Electrical Components & Equipment" },
  "ETR": { sector: "Utilities", subsector: "Electric Utilities" },
  "EVRG": { sector: "Utilities", subsector: "Electric Utilities" },
  "EW": { sector: "Health Care", subsector: "Health Care Equipment" },
  "EWG": { sector: "Broad Market", subsector: "Equity ETF" },
  "EWJ": { sector: "Broad Market", subsector: "Equity ETF" },
  "EWQ": { sector: "Broad Market", subsector: "Equity ETF" },
  "EWU": { sector: "Broad Market", subsector: "Equity ETF" },
  "EWW": { sector: "Broad Market", subsector: "Equity ETF" },
  "EWY": { sector: "Broad Market", subsector: "Equity ETF" },
  "EWZ": { sector: "Broad Market", subsector: "Equity ETF" },
  "EXC": { sector: "Utilities", subsector: "Electric Utilities" },
  "EXE": { sector: "Energy", subsector: "Oil & Gas Exploration & Production" },
  "EXPD": { sector: "Industrials", subsector: "Air Freight & Logistics" },
  "EXPE": { sector: "Consumer Discretionary", subsector: "Hotels, Resorts & Cruise Lines" },
  "EXR": { sector: "Real Estate", subsector: "Self-Storage REITs" },
  "F": { sector: "Consumer Discretionary", subsector: "Automobile Manufacturers" },
  "FAC": { sector: "Financials", subsector: "Insurance" },
  "FANG": { sector: "Energy", subsector: "Oil & Gas Exploration & Production" },
  "FAS": { sector: "Financials", subsector: "Leveraged ETF" },
  "FAST": { sector: "Industrials", subsector: "Trading Companies & Distributors" },
  "FAZ": { sector: "Financials", subsector: "Inverse ETF" },
  "FBTC": { sector: "Digital Assets", subsector: "Bitcoin ETF" },
  "FCEL": { sector: "Industrials", subsector: "Clean Energy" },
  "FCX": { sector: "Materials", subsector: "Copper" },
  "FDS": { sector: "Financials", subsector: "Financial Exchanges & Data" },
  "FDX": { sector: "Industrials", subsector: "Air Freight & Logistics" },
  "FDXF": { sector: "Industrials", subsector: "Cargo Ground Transportation" },
  "FE": { sector: "Utilities", subsector: "Electric Utilities" },
  "FEZ": { sector: "Broad Market", subsector: "Equity ETF" },
  "FFIV": { sector: "Information Technology", subsector: "Communications Equipment" },
  "FICO": { sector: "Information Technology", subsector: "Application Software" },
  "FINX": { sector: "Financials", subsector: "Thematic ETF" },
  "FIS": { sector: "Financials", subsector: "Transaction & Payment Processing Services" },
  "FISV": { sector: "Financials", subsector: "Transaction & Payment Processing Services" },
  "FITB": { sector: "Financials", subsector: "Regional Banks" },
  "FIX": { sector: "Industrials", subsector: "Construction & Engineering" },
  "FLQM": { sector: "Broad Market", subsector: "Equity ETF" },
  "FN": { sector: "Information Technology", subsector: "Optical Components" },
  "FOX": { sector: "Communication Services", subsector: "Broadcasting" },
  "FOXA": { sector: "Communication Services", subsector: "Broadcasting" },
  "FRT": { sector: "Real Estate", subsector: "Retail REITs" },
  "FSLR": { sector: "Information Technology", subsector: "Semiconductors" },
  "FTNT": { sector: "Information Technology", subsector: "Systems Software" },
  "FTV": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "FXI": { sector: "Broad Market", subsector: "Equity ETF" },
  "GD": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "GDDY": { sector: "Information Technology", subsector: "Internet Services & Infrastructure" },
  "GE": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "GEHC": { sector: "Health Care", subsector: "Health Care Equipment" },
  "GEN": { sector: "Information Technology", subsector: "Systems Software" },
  "GEV": { sector: "Industrials", subsector: "Heavy Electrical Equipment" },
  "GFS": { sector: "Information Technology", subsector: "Semiconductor Foundry" },
  "GILD": { sector: "Health Care", subsector: "Biotechnology" },
  "GIS": { sector: "Consumer Staples", subsector: "Packaged Foods & Meats" },
  "GL": { sector: "Financials", subsector: "Life & Health Insurance" },
  "GLBE": { sector: "Information Technology", subsector: "E-Commerce Platform" },
  "GLDM": { sector: "Commodities", subsector: "Commodity ETF" },
  "GLW": { sector: "Information Technology", subsector: "Electronic Components" },
  "GM": { sector: "Consumer Discretionary", subsector: "Automobile Manufacturers" },
  "GME": { sector: "Consumer Discretionary", subsector: "Gaming Retail" },
  "GNRC": { sector: "Industrials", subsector: "Electrical Components & Equipment" },
  "GOF": { sector: "Fixed Income", subsector: "Closed-End Fund" },
  "GOOG": { sector: "Communication Services", subsector: "Interactive Media & Services" },
  "GOOGL": { sector: "Communication Services", subsector: "Interactive Media & Services" },
  "GOVT": { sector: "Fixed Income", subsector: "Bond ETF" },
  "GPC": { sector: "Consumer Discretionary", subsector: "Distributors" },
  "GPN": { sector: "Financials", subsector: "Transaction & Payment Processing Services" },
  "GRMN": { sector: "Consumer Discretionary", subsector: "Consumer Electronics" },
  "GS": { sector: "Financials", subsector: "Investment Banking & Brokerage" },
  "GSG": { sector: "Commodities", subsector: "Commodity ETF" },
  "GWW": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "HAL": { sector: "Energy", subsector: "Oil & Gas Equipment & Services" },
  "HAS": { sector: "Consumer Discretionary", subsector: "Leisure Products" },
  "HBAN": { sector: "Financials", subsector: "Regional Banks" },
  "HCA": { sector: "Health Care", subsector: "Health Care Facilities" },
  "HD": { sector: "Consumer Discretionary", subsector: "Home Improvement Retail" },
  "HES": { sector: "Energy", subsector: "E&P" },
  "HIG": { sector: "Financials", subsector: "Property & Casualty Insurance" },
  "HII": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "HIMS": { sector: "Health Care", subsector: "Telehealth" },
  "HIVE": { sector: "Digital Assets", subsector: "Crypto Mining" },
  "HLT": { sector: "Consumer Discretionary", subsector: "Hotels, Resorts & Cruise Lines" },
  "HODL": { sector: "Digital Assets", subsector: "Bitcoin ETF" },
  "HOLX": { sector: "Health Care", subsector: "Diagnostics" },
  "HON": { sector: "Industrials", subsector: "Industrial Conglomerates" },
  "HOOD": { sector: "Financials", subsector: "Investment Banking & Brokerage" },
  "HPE": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "HPQ": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "HRL": { sector: "Consumer Staples", subsector: "Packaged Foods & Meats" },
  "HSIC": { sector: "Health Care", subsector: "Health Care Distributors" },
  "HST": { sector: "Real Estate", subsector: "Hotel & Resort REITs" },
  "HSY": { sector: "Consumer Staples", subsector: "Packaged Foods & Meats" },
  "HUBB": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "HUBS": { sector: "Information Technology", subsector: "Software" },
  "HUM": { sector: "Health Care", subsector: "Managed Health Care" },
  "HUT": { sector: "Digital Assets", subsector: "Crypto Mining" },
  "HWM": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "HYLN": { sector: "Industrials", subsector: "EV Powertrain" },
  "IAU": { sector: "Commodities", subsector: "Commodity ETF" },
  "IBB": { sector: "Health Care", subsector: "Sector ETF" },
  "IBIT": { sector: "Digital Assets", subsector: "Bitcoin ETF" },
  "IBKR": { sector: "Financials", subsector: "Investment Banking & Brokerage" },
  "IBM": { sector: "Information Technology", subsector: "IT Consulting & Other Services" },
  "ICE": { sector: "Financials", subsector: "Financial Exchanges & Data" },
  "ICLN": { sector: "Information Technology", subsector: "Thematic ETF" },
  "IDRV": { sector: "Consumer Discretionary", subsector: "Thematic ETF" },
  "IDXX": { sector: "Health Care", subsector: "Health Care Equipment" },
  "IEF": { sector: "Fixed Income", subsector: "Bond ETF" },
  "IEFA": { sector: "Broad Market", subsector: "Equity ETF" },
  "IEMG": { sector: "Broad Market", subsector: "Equity ETF" },
  "IEX": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "IFF": { sector: "Materials", subsector: "Specialty Chemicals" },
  "IJH": { sector: "Broad Market", subsector: "Equity ETF" },
  "IJR": { sector: "Broad Market", subsector: "Equity ETF" },
  "IJS": { sector: "Broad Market", subsector: "Equity ETF" },
  "IJT": { sector: "Broad Market", subsector: "Equity ETF" },
  "ILF": { sector: "Broad Market", subsector: "Equity ETF" },
  "INCY": { sector: "Health Care", subsector: "Biotechnology" },
  "INDA": { sector: "Broad Market", subsector: "Equity ETF" },
  "INHD": { sector: "Information Technology", subsector: "Hardware" },
  "INTC": { sector: "Information Technology", subsector: "Semiconductors" },
  "INTU": { sector: "Information Technology", subsector: "Application Software" },
  "INVH": { sector: "Real Estate", subsector: "Single-Family Residential REITs" },
  "IONQ": { sector: "Information Technology", subsector: "Quantum Computing" },
  "IOT": { sector: "Information Technology", subsector: "IoT Platform" },
  "IP": { sector: "Materials", subsector: "Paper & Plastic Packaging Products & Materials" },
  "IPAY": { sector: "Financials", subsector: "Thematic ETF" },
  "IPG": { sector: "Communication Services", subsector: "Advertising" },
  "IPWR": { sector: "Industrials", subsector: "Clean Energy" },
  "IQE": { sector: "Information Technology", subsector: "Semiconductors" },
  "IQV": { sector: "Health Care", subsector: "Life Sciences Tools & Services" },
  "IR": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "IREN": { sector: "Digital Assets", subsector: "Crypto Mining" },
  "IRM": { sector: "Real Estate", subsector: "Other Specialized REITs" },
  "ISRG": { sector: "Health Care", subsector: "Health Care Equipment" },
  "IT": { sector: "Information Technology", subsector: "IT Consulting & Other Services" },
  "ITOT": { sector: "Broad Market", subsector: "Equity ETF" },
  "ITW": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "IVZ": { sector: "Financials", subsector: "Asset Management & Custody Banks" },
  "IWB": { sector: "Broad Market", subsector: "Equity ETF" },
  "IWD": { sector: "Broad Market", subsector: "Equity ETF" },
  "IWF": { sector: "Broad Market", subsector: "Equity ETF" },
  "IWM": { sector: "Broad Market", subsector: "Equity ETF" },
  "IWV": { sector: "Broad Market", subsector: "Equity ETF" },
  "IYR": { sector: "Real Estate", subsector: "Sector ETF" },
  "J": { sector: "Industrials", subsector: "Construction & Engineering" },
  "JBHT": { sector: "Industrials", subsector: "Cargo Ground Transportation" },
  "JBL": { sector: "Information Technology", subsector: "Electronic Manufacturing Services" },
  "JCI": { sector: "Industrials", subsector: "Building Products" },
  "JEPI": { sector: "Broad Market", subsector: "Covered Call ETF" },
  "JEPQ": { sector: "Broad Market", subsector: "Covered Call ETF" },
  "JKHY": { sector: "Financials", subsector: "Transaction & Payment Processing Services" },
  "JNJ": { sector: "Health Care", subsector: "Pharmaceuticals" },
  "JNK": { sector: "Fixed Income", subsector: "Bond ETF" },
  "JOBY": { sector: "Industrials", subsector: "Defense & Space" },
  "JPM": { sector: "Financials", subsector: "Diversified Banks" },
  "JPST": { sector: "Fixed Income", subsector: "Yield ETF" },
  "K": { sector: "Consumer Staples", subsector: "Packaged Foods" },
  "KBE": { sector: "Financials", subsector: "Sector ETF" },
  "KDP": { sector: "Consumer Staples", subsector: "Soft Drinks & Non-alcoholic Beverages" },
  "KEY": { sector: "Financials", subsector: "Regional Banks" },
  "KEYS": { sector: "Information Technology", subsector: "Electronic Equipment & Instruments" },
  "KHC": { sector: "Consumer Staples", subsector: "Packaged Foods & Meats" },
  "KIM": { sector: "Real Estate", subsector: "Retail REITs" },
  "KKR": { sector: "Financials", subsector: "Asset Management & Custody Banks" },
  "KLAC": { sector: "Information Technology", subsector: "Semiconductor Materials & Equipment" },
  "KMB": { sector: "Consumer Staples", subsector: "Household Products" },
  "KMI": { sector: "Energy", subsector: "Oil & Gas Storage & Transportation" },
  "KMX": { sector: "Consumer Discretionary", subsector: "Auto Retail" },
  "KO": { sector: "Consumer Staples", subsector: "Soft Drinks & Non-alcoholic Beverages" },
  "KR": { sector: "Consumer Staples", subsector: "Food Retail" },
  "KRE": { sector: "Financials", subsector: "Sector ETF" },
  "KTOS": { sector: "Industrials", subsector: "Defense & Space" },
  "KVUE": { sector: "Consumer Staples", subsector: "Personal Care Products" },
  "KWEB": { sector: "Broad Market", subsector: "Equity ETF" },
  "L": { sector: "Financials", subsector: "Multi-line Insurance" },
  "LABU": { sector: "Health Care", subsector: "Leveraged ETF" },
  "LCID": { sector: "Consumer Discretionary", subsector: "EV" },
  "LDOS": { sector: "Industrials", subsector: "Diversified Support Services" },
  "LEN": { sector: "Consumer Discretionary", subsector: "Homebuilding" },
  "LEU": { sector: "Energy", subsector: "Nuclear Fuel" },
  "LFUS": { sector: "Information Technology", subsector: "Electronic Components" },
  "LH": { sector: "Health Care", subsector: "Health Care Services" },
  "LHX": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "LII": { sector: "Industrials", subsector: "Building Products" },
  "LIN": { sector: "Materials", subsector: "Industrial Gases" },
  "LIT": { sector: "Materials", subsector: "Thematic ETF" },
  "LITE": { sector: "Information Technology", subsector: "Communications Equipment" },
  "LKQ": { sector: "Consumer Discretionary", subsector: "Auto Parts" },
  "LLY": { sector: "Health Care", subsector: "Pharmaceuticals" },
  "LMT": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "LNG": { sector: "Energy", subsector: "LNG" },
  "LNT": { sector: "Utilities", subsector: "Electric Utilities" },
  "LOW": { sector: "Consumer Discretionary", subsector: "Home Improvement Retail" },
  "LPK": { sector: "Information Technology", subsector: "Semiconductor Materials & Equipment" },
  "LRCX": { sector: "Information Technology", subsector: "Semiconductor Materials & Equipment" },
  "LULU": { sector: "Consumer Discretionary", subsector: "Apparel, Accessories & Luxury Goods" },
  "LUMN": { sector: "Communication Services", subsector: "Telecom" },
  "LUNR": { sector: "Industrials", subsector: "Defense & Space" },
  "LUV": { sector: "Industrials", subsector: "Passenger Airlines" },
  "LVS": { sector: "Consumer Discretionary", subsector: "Casinos & Gaming" },
  "LWLG": { sector: "Information Technology", subsector: "Semiconductor Materials & Equipment" },
  "LYB": { sector: "Materials", subsector: "Specialty Chemicals" },
  "LYV": { sector: "Communication Services", subsector: "Movies & Entertainment" },
  "MA": { sector: "Financials", subsector: "Transaction & Payment Processing Services" },
  "MAA": { sector: "Real Estate", subsector: "Multi-Family Residential REITs" },
  "MAR": { sector: "Consumer Discretionary", subsector: "Hotels, Resorts & Cruise Lines" },
  "MARA": { sector: "Digital Assets", subsector: "Crypto Mining" },
  "MAS": { sector: "Industrials", subsector: "Building Products" },
  "MCD": { sector: "Consumer Discretionary", subsector: "Restaurants" },
  "MCHP": { sector: "Information Technology", subsector: "Semiconductors" },
  "MCK": { sector: "Health Care", subsector: "Health Care Distributors" },
  "MCO": { sector: "Financials", subsector: "Financial Exchanges & Data" },
  "MDB": { sector: "Information Technology", subsector: "Software" },
  "MDLZ": { sector: "Consumer Staples", subsector: "Packaged Foods & Meats" },
  "MDT": { sector: "Health Care", subsector: "Health Care Equipment" },
  "MDY": { sector: "Broad Market", subsector: "Equity ETF" },
  "MEDP": { sector: "Health Care", subsector: "Life Sciences CRO" },
  "MET": { sector: "Financials", subsector: "Life & Health Insurance" },
  "META": { sector: "Communication Services", subsector: "Interactive Media & Services" },
  "MGM": { sector: "Consumer Discretionary", subsector: "Casinos & Gaming" },
  "MKC": { sector: "Consumer Staples", subsector: "Packaged Foods & Meats" },
  "MKTX": { sector: "Financials", subsector: "Electronic Trading" },
  "MLM": { sector: "Materials", subsector: "Construction Materials" },
  "MMC": { sector: "Financials", subsector: "Insurance Brokerage" },
  "MMM": { sector: "Industrials", subsector: "Industrial Conglomerates" },
  "MNST": { sector: "Consumer Staples", subsector: "Soft Drinks & Non-alcoholic Beverages" },
  "MO": { sector: "Consumer Staples", subsector: "Tobacco" },
  "MOD": { sector: "Industrials", subsector: "HVAC" },
  "MOH": { sector: "Health Care", subsector: "Managed Care" },
  "MOO": { sector: "Broad Market", subsector: "Equity ETF" },
  "MOS": { sector: "Materials", subsector: "Fertilizers & Agricultural Chemicals" },
  "MPC": { sector: "Energy", subsector: "Oil & Gas Refining & Marketing" },
  "MPWR": { sector: "Information Technology", subsector: "Semiconductors" },
  "MRK": { sector: "Health Care", subsector: "Pharmaceuticals" },
  "MRNA": { sector: "Health Care", subsector: "Biotechnology" },
  "MRAM": { sector: "Information Technology", subsector: "Semiconductors" },
  "MRO": { sector: "Energy", subsector: "E&P" },
  "MRSH": { sector: "Financials", subsector: "Insurance Brokers" },
  "MS": { sector: "Financials", subsector: "Investment Banking & Brokerage" },
  "MSCI": { sector: "Financials", subsector: "Financial Exchanges & Data" },
  "MSFT": { sector: "Information Technology", subsector: "Systems Software" },
  "MSI": { sector: "Information Technology", subsector: "Communications Equipment" },
  "MSTR": { sector: "Digital Assets", subsector: "Bitcoin Treasury" },
  "MTB": { sector: "Financials", subsector: "Regional Banks" },
  "MTD": { sector: "Health Care", subsector: "Life Sciences Tools & Services" },
  "MTSI": { sector: "Information Technology", subsector: "Semiconductors" },
  "MTUM": { sector: "Broad Market", subsector: "Factor ETF" },
  "MU": { sector: "Information Technology", subsector: "Semiconductors" },
  "NBIS": { sector: "Information Technology", subsector: "Cloud Infrastructure" },
  "NCLH": { sector: "Consumer Discretionary", subsector: "Hotels, Resorts & Cruise Lines" },
  "NDAQ": { sector: "Financials", subsector: "Financial Exchanges & Data" },
  "NDSN": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "NEE": { sector: "Utilities", subsector: "Multi-Utilities" },
  "NEM": { sector: "Materials", subsector: "Gold" },
  "NET": { sector: "Information Technology", subsector: "CDN & Security" },
  "NFLX": { sector: "Communication Services", subsector: "Movies & Entertainment" },
  "NI": { sector: "Utilities", subsector: "Multi-Utilities" },
  "NKE": { sector: "Consumer Discretionary", subsector: "Apparel, Accessories & Luxury Goods" },
  "NKLA": { sector: "Industrials", subsector: "EV" },
  "NOC": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "NOW": { sector: "Information Technology", subsector: "Systems Software" },
  "NRG": { sector: "Utilities", subsector: "Independent Power Producers & Energy Traders" },
  "NSC": { sector: "Industrials", subsector: "Rail Transportation" },
  "NTAP": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "NTNX": { sector: "Information Technology", subsector: "Cloud Infrastructure" },
  "NTRS": { sector: "Financials", subsector: "Asset Management & Custody Banks" },
  "NU": { sector: "Financials", subsector: "Fintech" },
  "NUE": { sector: "Materials", subsector: "Steel" },
  "NUSI": { sector: "Broad Market", subsector: "Covered Call ETF" },
  "NVDA": { sector: "Information Technology", subsector: "Semiconductors" },
  "NVO": { sector: "Health Care", subsector: "Biopharma" },
  "NVR": { sector: "Consumer Discretionary", subsector: "Homebuilding" },
  "NVTS": { sector: "Information Technology", subsector: "Semiconductors" },
  "NWS": { sector: "Communication Services", subsector: "Publishing" },
  "NWSA": { sector: "Communication Services", subsector: "Publishing" },
  "NXPI": { sector: "Information Technology", subsector: "Semiconductors" },
  "O": { sector: "Real Estate", subsector: "Retail REITs" },
  "ODFL": { sector: "Industrials", subsector: "Cargo Ground Transportation" },
  "OKE": { sector: "Energy", subsector: "Oil & Gas Storage & Transportation" },
  "OKLO": { sector: "Energy", subsector: "Advanced Nuclear" },
  "OKTA": { sector: "Information Technology", subsector: "Cybersecurity" },
  "OMC": { sector: "Communication Services", subsector: "Advertising" },
  "ON": { sector: "Information Technology", subsector: "Semiconductors" },
  "ONDS": { sector: "Industrials", subsector: "Drone Tech" },
  "OPEN": { sector: "Consumer Discretionary", subsector: "Real Estate Tech" },
  "ORCL": { sector: "Information Technology", subsector: "Application Software" },
  "ORLY": { sector: "Consumer Discretionary", subsector: "Automotive Retail" },
  "OTIS": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "OXY": { sector: "Energy", subsector: "Oil & Gas Exploration & Production" },
  "PANW": { sector: "Information Technology", subsector: "Systems Software" },
  "PARA": { sector: "Communication Services", subsector: "Media" },
  "PAYX": { sector: "Industrials", subsector: "Human Resource & Employment Services" },
  "PBD": { sector: "Information Technology", subsector: "Thematic ETF" },
  "PBW": { sector: "Information Technology", subsector: "Thematic ETF" },
  "PCAR": { sector: "Industrials", subsector: "Construction Machinery & Heavy Transportation Equipment" },
  "PCG": { sector: "Utilities", subsector: "Multi-Utilities" },
  "PCY": { sector: "Fixed Income", subsector: "Bond ETF" },
  "PDI": { sector: "Fixed Income", subsector: "Closed-End Fund" },
  "PEG": { sector: "Utilities", subsector: "Electric Utilities" },
  "PEP": { sector: "Consumer Staples", subsector: "Soft Drinks & Non-alcoholic Beverages" },
  "PFE": { sector: "Health Care", subsector: "Pharmaceuticals" },
  "PFF": { sector: "Fixed Income", subsector: "Preferred ETF" },
  "PFG": { sector: "Financials", subsector: "Life & Health Insurance" },
  "PG": { sector: "Consumer Staples", subsector: "Personal Care Products" },
  "PGR": { sector: "Financials", subsector: "Property & Casualty Insurance" },
  "PGX": { sector: "Fixed Income", subsector: "Preferred ETF" },
  "PH": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "PHM": { sector: "Consumer Discretionary", subsector: "Homebuilding" },
  "PKG": { sector: "Materials", subsector: "Paper & Plastic Packaging Products & Materials" },
  "PLD": { sector: "Real Estate", subsector: "Industrial REITs" },
  "PLTR": { sector: "Information Technology", subsector: "Application Software" },
  "PLUG": { sector: "Industrials", subsector: "Hydrogen Energy" },
  "PM": { sector: "Consumer Staples", subsector: "Tobacco" },
  "PNC": { sector: "Financials", subsector: "Diversified Banks" },
  "PNR": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "PNW": { sector: "Utilities", subsector: "Multi-Utilities" },
  "PODD": { sector: "Health Care", subsector: "Health Care Equipment" },
  "POET": { sector: "Information Technology", subsector: "Photonics" },
  "POOL": { sector: "Consumer Discretionary", subsector: "Distributors" },
  "POWI": { sector: "Information Technology", subsector: "Semiconductors" },
  "PPG": { sector: "Materials", subsector: "Specialty Chemicals" },
  "PPL": { sector: "Utilities", subsector: "Electric Utilities" },
  "PRNT": { sector: "Industrials", subsector: "Thematic ETF" },
  "PRU": { sector: "Financials", subsector: "Life & Health Insurance" },
  "PSA": { sector: "Real Estate", subsector: "Self-Storage REITs" },
  "PSKY": { sector: "Communication Services", subsector: "Movies & Entertainment" },
  "PSQ": { sector: "Broad Market", subsector: "Inverse ETF" },
  "PSX": { sector: "Energy", subsector: "Oil & Gas Refining & Marketing" },
  "PTC": { sector: "Information Technology", subsector: "Application Software" },
  "PWR": { sector: "Industrials", subsector: "Construction & Engineering" },
  "PYPL": { sector: "Financials", subsector: "Transaction & Payment Processing Services" },
  "Q": { sector: "Information Technology", subsector: "Semiconductor Materials & Equipment" },
  "QBTS": { sector: "Information Technology", subsector: "Quantum Computing" },
  "QCLN": { sector: "Information Technology", subsector: "Thematic ETF" },
  "QCOM": { sector: "Information Technology", subsector: "Semiconductors" },
  "QLD": { sector: "Broad Market", subsector: "Leveraged ETF" },
  "QQQ": { sector: "Broad Market", subsector: "Equity ETF" },
  "QRVO": { sector: "Information Technology", subsector: "Semiconductors" },
  "QUAL": { sector: "Broad Market", subsector: "Factor ETF" },
  "QUBT": { sector: "Information Technology", subsector: "Quantum Computing" },
  "QYLD": { sector: "Broad Market", subsector: "Covered Call ETF" },
  "RBLX": { sector: "Communication Services", subsector: "Gaming Platform" },
  "RCL": { sector: "Consumer Discretionary", subsector: "Hotels, Resorts & Cruise Lines" },
  "RDDT": { sector: "Communication Services", subsector: "Social Media" },
  "REET": { sector: "Real Estate", subsector: "Real Estate ETF" },
  "REG": { sector: "Real Estate", subsector: "Retail REITs" },
  "REGN": { sector: "Health Care", subsector: "Biotechnology" },
  "RELL": { sector: "Industrials", subsector: "Electronics Distribution" },
  "REMX": { sector: "Materials", subsector: "Thematic ETF" },
  "RF": { sector: "Financials", subsector: "Regional Banks" },
  "RGTI": { sector: "Information Technology", subsector: "Quantum Computing" },
  "RIOT": { sector: "Digital Assets", subsector: "Crypto Mining" },
  "RIVN": { sector: "Consumer Discretionary", subsector: "EV" },
  "RJF": { sector: "Financials", subsector: "Investment Banking & Brokerage" },
  "RKLB": { sector: "Industrials", subsector: "Defense & Space" },
  "RL": { sector: "Consumer Discretionary", subsector: "Apparel, Accessories & Luxury Goods" },
  "RMD": { sector: "Health Care", subsector: "Health Care Equipment" },
  "ROBO": { sector: "Information Technology", subsector: "Thematic ETF" },
  "ROK": { sector: "Industrials", subsector: "Electrical Components & Equipment" },
  "ROKU": { sector: "Consumer Discretionary", subsector: "Streaming Devices" },
  "ROL": { sector: "Industrials", subsector: "Environmental & Facilities Services" },
  "ROP": { sector: "Information Technology", subsector: "Electronic Equipment & Instruments" },
  "RPI": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "ROST": { sector: "Consumer Discretionary", subsector: "Apparel Retail" },
  "RSG": { sector: "Industrials", subsector: "Environmental & Facilities Services" },
  "RTX": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "RVTY": { sector: "Health Care", subsector: "Health Care Equipment" },
  "RXRX": { sector: "Health Care", subsector: "AI Drug Discovery" },
  "S": { sector: "Information Technology", subsector: "Cybersecurity" },
  "SATS": { sector: "Communication Services", subsector: "Wireless Telecommunication Services" },
  "SBAC": { sector: "Real Estate", subsector: "Telecom Tower REITs" },
  "SBUX": { sector: "Consumer Discretionary", subsector: "Restaurants" },
  "SCHB": { sector: "Broad Market", subsector: "Equity ETF" },
  "SCHD": { sector: "Broad Market", subsector: "Dividend ETF" },
  "SCHF": { sector: "Broad Market", subsector: "Equity ETF" },
  "SCHH": { sector: "Real Estate", subsector: "Real Estate ETF" },
  "SCHM": { sector: "Broad Market", subsector: "Equity ETF" },
  "SCHO": { sector: "Fixed Income", subsector: "Bond ETF" },
  "SCHR": { sector: "Fixed Income", subsector: "Bond ETF" },
  "SCHW": { sector: "Financials", subsector: "Investment Banking & Brokerage" },
  "SCHX": { sector: "Broad Market", subsector: "Equity ETF" },
  "SCHZ": { sector: "Fixed Income", subsector: "Bond ETF" },
  "SCZ": { sector: "Broad Market", subsector: "Equity ETF" },
  "SDS": { sector: "Broad Market", subsector: "Inverse ETF" },
  "SEDG": { sector: "Information Technology", subsector: "Solar Equipment" },
  "SGOV": { sector: "Fixed Income", subsector: "Yield ETF" },
  "SH": { sector: "Broad Market", subsector: "Inverse ETF" },
  "SHOP": { sector: "Information Technology", subsector: "E-Commerce Platform" },
  "SHW": { sector: "Materials", subsector: "Specialty Chemicals" },
  "SIVE": { sector: "Information Technology", subsector: "Semiconductor Equipment" },
  "SIZE": { sector: "Broad Market", subsector: "Factor ETF" },
  "SJM": { sector: "Consumer Staples", subsector: "Packaged Foods & Meats" },
  "SKYY": { sector: "Information Technology", subsector: "Thematic ETF" },
  "SLB": { sector: "Energy", subsector: "Oil & Gas Equipment & Services" },
  "SLNH": { sector: "Information Technology", subsector: "Data Center Cooling" },
  "SMCI": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "SMR": { sector: "Energy", subsector: "Nuclear Reactors" },
  "SNA": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "SNAP": { sector: "Communication Services", subsector: "Social Media" },
  "SNDK": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "SNOW": { sector: "Information Technology", subsector: "Data Platform" },
  "SNPS": { sector: "Information Technology", subsector: "Application Software" },
  "SO": { sector: "Utilities", subsector: "Electric Utilities" },
  "SOCL": { sector: "Communication Services", subsector: "Thematic ETF" },
  "SOFI": { sector: "Financials", subsector: "Fintech" },
  "SOI": { sector: "Information Technology", subsector: "Semiconductors" },
  "SOLV": { sector: "Health Care", subsector: "Health Care Technology" },
  "SOUN": { sector: "Information Technology", subsector: "AI Voice" },
  "SOXS": { sector: "Information Technology", subsector: "Inverse ETF" },
  "SPCE": { sector: "Industrials", subsector: "Space Tourism" },
  "SPG": { sector: "Real Estate", subsector: "Retail REITs" },
  "SPGI": { sector: "Financials", subsector: "Financial Exchanges & Data" },
  "SPHD": { sector: "Broad Market", subsector: "Dividend ETF" },
  "SPLV": { sector: "Broad Market", subsector: "Factor ETF" },
  "SPOT": { sector: "Communication Services", subsector: "Audio Streaming" },
  "SPXL": { sector: "Broad Market", subsector: "Leveraged ETF" },
  "SPXS": { sector: "Broad Market", subsector: "Inverse ETF" },
  "SPY": { sector: "Broad Market", subsector: "Equity ETF" },
  "SQ": { sector: "Financials", subsector: "Fintech" },
  "SQQQ": { sector: "Broad Market", subsector: "Inverse ETF" },
  "SRE": { sector: "Utilities", subsector: "Multi-Utilities" },
  "SRVR": { sector: "Real Estate", subsector: "Data Center ETF" },
  "SSO": { sector: "Broad Market", subsector: "Leveraged ETF" },
  "STE": { sector: "Health Care", subsector: "Health Care Equipment" },
  "STLD": { sector: "Materials", subsector: "Steel" },
  "STT": { sector: "Financials", subsector: "Asset Management & Custody Banks" },
  "STX": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "STZ": { sector: "Consumer Staples", subsector: "Distillers & Vintners" },
  "SW": { sector: "Materials", subsector: "Paper & Plastic Packaging Products & Materials" },
  "SWK": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "SWKS": { sector: "Information Technology", subsector: "Semiconductors" },
  "SYF": { sector: "Financials", subsector: "Consumer Finance" },
  "SYK": { sector: "Health Care", subsector: "Health Care Equipment" },
  "SYY": { sector: "Consumer Staples", subsector: "Food Distributors" },
  "T": { sector: "Communication Services", subsector: "Integrated Telecommunication Services" },
  "TAN": { sector: "Information Technology", subsector: "Thematic ETF" },
  "TAP": { sector: "Consumer Staples", subsector: "Brewers" },
  "TDG": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "TDY": { sector: "Information Technology", subsector: "Electronic Equipment & Instruments" },
  "TEAM": { sector: "Information Technology", subsector: "Software" },
  "TECH": { sector: "Health Care", subsector: "Life Sciences Tools & Services" },
  "TECL": { sector: "Broad Market", subsector: "Leveraged ETF" },
  "TEL": { sector: "Information Technology", subsector: "Electronic Manufacturing Services" },
  "TER": { sector: "Information Technology", subsector: "Semiconductor Materials & Equipment" },
  "TFC": { sector: "Financials", subsector: "Diversified Banks" },
  "TGT": { sector: "Consumer Staples", subsector: "Consumer Staples Merchandise Retail" },
  "TIP": { sector: "Fixed Income", subsector: "Bond ETF" },
  "TJX": { sector: "Consumer Discretionary", subsector: "Apparel Retail" },
  "TKO": { sector: "Communication Services", subsector: "Movies & Entertainment" },
  "TMO": { sector: "Health Care", subsector: "Life Sciences Tools & Services" },
  "TMUS": { sector: "Communication Services", subsector: "Wireless Telecommunication Services" },
  "TOLZ": { sector: "Real Estate", subsector: "Infra ETF" },
  "TOST": { sector: "Information Technology", subsector: "Restaurant SaaS" },
  "TPL": { sector: "Energy", subsector: "Oil & Gas Exploration & Production" },
  "TPR": { sector: "Consumer Discretionary", subsector: "Apparel, Accessories & Luxury Goods" },
  "TQQQ": { sector: "Broad Market", subsector: "Leveraged ETF" },
  "TRGP": { sector: "Energy", subsector: "Oil & Gas Storage & Transportation" },
  "TRMB": { sector: "Information Technology", subsector: "Application Software" },
  "TROW": { sector: "Financials", subsector: "Asset Management & Custody Banks" },
  "TRV": { sector: "Financials", subsector: "Property & Casualty Insurance" },
  "TSCO": { sector: "Consumer Discretionary", subsector: "Other Specialty Retail" },
  "TSEM": { sector: "Information Technology", subsector: "Semiconductors" },
  "TSLA": { sector: "Consumer Discretionary", subsector: "Automobile Manufacturers" },
  "TSM": { sector: "Information Technology", subsector: "Semiconductors" },
  "TSN": { sector: "Consumer Staples", subsector: "Packaged Foods & Meats" },
  "TT": { sector: "Industrials", subsector: "Building Products" },
  "TTD": { sector: "Communication Services", subsector: "Advertising" },
  "TTWO": { sector: "Communication Services", subsector: "Interactive Home Entertainment" },
  "TWLO": { sector: "Information Technology", subsector: "Communications API" },
  "TXN": { sector: "Information Technology", subsector: "Semiconductors" },
  "TXT": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "TYL": { sector: "Information Technology", subsector: "Application Software" },
  "U": { sector: "Information Technology", subsector: "Game Engine" },
  "UAL": { sector: "Industrials", subsector: "Passenger Airlines" },
  "UBER": { sector: "Industrials", subsector: "Passenger Ground Transportation" },
  "UDR": { sector: "Real Estate", subsector: "Multi-Family Residential REITs" },
  "UEC": { sector: "Energy", subsector: "Uranium Mining" },
  "UGA": { sector: "Commodities", subsector: "Commodity ETF" },
  "UHS": { sector: "Health Care", subsector: "Health Care Facilities" },
  "ULTA": { sector: "Consumer Discretionary", subsector: "Other Specialty Retail" },
  "UNG": { sector: "Commodities", subsector: "Commodity ETF" },
  "UNH": { sector: "Health Care", subsector: "Managed Health Care" },
  "UNP": { sector: "Industrials", subsector: "Rail Transportation" },
  "UPRO": { sector: "Broad Market", subsector: "Leveraged ETF" },
  "UPS": { sector: "Industrials", subsector: "Air Freight & Logistics" },
  "UPST": { sector: "Financials", subsector: "Fintech" },
  "URI": { sector: "Industrials", subsector: "Trading Companies & Distributors" },
  "USB": { sector: "Financials", subsector: "Diversified Banks" },
  "USCI": { sector: "Commodities", subsector: "Commodity ETF" },
  "USMV": { sector: "Broad Market", subsector: "Factor ETF" },
  "USPX": { sector: "Broad Market", subsector: "Equity ETF" },
  "V": { sector: "Financials", subsector: "Transaction & Payment Processing Services" },
  "VCIT": { sector: "Fixed Income", subsector: "Bond ETF" },
  "VCLT": { sector: "Fixed Income", subsector: "Bond ETF" },
  "VCSH": { sector: "Fixed Income", subsector: "Bond ETF" },
  "VEA": { sector: "Broad Market", subsector: "Equity ETF" },
  "VEEV": { sector: "Health Care", subsector: "Health Care Technology" },
  "VEU": { sector: "Broad Market", subsector: "Equity ETF" },
  "VFS": { sector: "Consumer Discretionary", subsector: "EV" },
  "VGK": { sector: "Broad Market", subsector: "Equity ETF" },
  "VICI": { sector: "Real Estate", subsector: "Hotel & Resort REITs" },
  "VICR": { sector: "Information Technology", subsector: "Power Components" },
  "VIVO": { sector: "Health Care", subsector: "Diagnostics" },
  "VKTX": { sector: "Health Care", subsector: "Biotech" },
  "VLO": { sector: "Energy", subsector: "Oil & Gas Refining & Marketing" },
  "VLTO": { sector: "Industrials", subsector: "Environmental & Facilities Services" },
  "VLUE": { sector: "Broad Market", subsector: "Factor ETF" },
  "VMC": { sector: "Materials", subsector: "Construction Materials" },
  "VNQ": { sector: "Real Estate", subsector: "Real Estate ETF" },
  "VOO": { sector: "Broad Market", subsector: "Equity ETF" },
  "VPN": { sector: "Real Estate", subsector: "Infra ETF" },
  "VRSK": { sector: "Industrials", subsector: "Research & Consulting Services" },
  "VRSN": { sector: "Information Technology", subsector: "Internet Services & Infrastructure" },
  "VRT": { sector: "Industrials", subsector: "Electrical Components & Equipment" },
  "VRTX": { sector: "Health Care", subsector: "Biotechnology" },
  "VSH": { sector: "Information Technology", subsector: "Electronic Components" },
  "VSS": { sector: "Broad Market", subsector: "Equity ETF" },
  "VST": { sector: "Utilities", subsector: "Electric Utilities" },
  "VT": { sector: "Broad Market", subsector: "Equity ETF" },
  "VTI": { sector: "Broad Market", subsector: "Equity ETF" },
  "VTR": { sector: "Real Estate", subsector: "Health Care REITs" },
  "VTRS": { sector: "Health Care", subsector: "Pharmaceuticals" },
  "VUG": { sector: "Broad Market", subsector: "Equity ETF" },
  "VWO": { sector: "Broad Market", subsector: "Equity ETF" },
  "VXF": { sector: "Broad Market", subsector: "Equity ETF" },
  "VXUS": { sector: "Broad Market", subsector: "Equity ETF" },
  "VYM": { sector: "Broad Market", subsector: "Dividend ETF" },
  "VZ": { sector: "Communication Services", subsector: "Integrated Telecommunication Services" },
  "WAB": { sector: "Industrials", subsector: "Construction Machinery & Heavy Transportation Equipment" },
  "WAT": { sector: "Health Care", subsector: "Life Sciences Tools & Services" },
  "WBA": { sector: "Consumer Staples", subsector: "Pharmacy Retail" },
  "WBD": { sector: "Communication Services", subsector: "Broadcasting" },
  "WCLD": { sector: "Information Technology", subsector: "Thematic ETF" },
  "WDAY": { sector: "Information Technology", subsector: "Application Software" },
  "WDC": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "WEC": { sector: "Utilities", subsector: "Electric Utilities" },
  "WELL": { sector: "Real Estate", subsector: "Health Care REITs" },
  "WFC": { sector: "Financials", subsector: "Diversified Banks" },
  "WGMI": { sector: "Digital Assets", subsector: "Crypto-Mining ETF" },
  "WING": { sector: "Consumer Discretionary", subsector: "Restaurants" },
  "WM": { sector: "Industrials", subsector: "Environmental & Facilities Services" },
  "WMB": { sector: "Energy", subsector: "Oil & Gas Storage & Transportation" },
  "WMT": { sector: "Consumer Staples", subsector: "Consumer Staples Merchandise Retail" },
  "WOLF": { sector: "Information Technology", subsector: "Semiconductors" },
  "WRB": { sector: "Financials", subsector: "Property & Casualty Insurance" },
  "WSM": { sector: "Consumer Discretionary", subsector: "Homefurnishing Retail" },
  "WST": { sector: "Health Care", subsector: "Health Care Supplies" },
  "WTW": { sector: "Financials", subsector: "Insurance Brokers" },
  "WULF": { sector: "Digital Assets", subsector: "Crypto Mining" },
  "WY": { sector: "Real Estate", subsector: "Timber REITs" },
  "WYNN": { sector: "Consumer Discretionary", subsector: "Casinos & Gaming" },
  "XBI": { sector: "Health Care", subsector: "Sector ETF" },
  "XEL": { sector: "Utilities", subsector: "Multi-Utilities" },
  "XFAB": { sector: "Information Technology", subsector: "Semiconductors" },
  "XHB": { sector: "Consumer Discretionary", subsector: "Sector ETF" },
  "XLB": { sector: "Materials", subsector: "Sector ETF" },
  "XLE": { sector: "Energy", subsector: "Energy ETF" },
  "XLF": { sector: "Financials", subsector: "Sector ETF" },
  "XLI": { sector: "Industrials", subsector: "Sector ETF" },
  "XLK": { sector: "Information Technology", subsector: "Sector ETF" },
  "XLP": { sector: "Consumer Staples", subsector: "Sector ETF" },
  "XLRE": { sector: "Real Estate", subsector: "Sector ETF" },
  "XLU": { sector: "Utilities", subsector: "Sector ETF" },
  "XLV": { sector: "Health Care", subsector: "Sector ETF" },
  "XLY": { sector: "Consumer Discretionary", subsector: "Sector ETF" },
  "XME": { sector: "Materials", subsector: "Sector ETF" },
  "XOM": { sector: "Energy", subsector: "Integrated Oil & Gas" },
  "XOP": { sector: "Energy", subsector: "E&P ETF" },
  "XRT": { sector: "Consumer Discretionary", subsector: "Sector ETF" },
  "XYL": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "XYLD": { sector: "Broad Market", subsector: "Covered Call ETF" },
  "XYZ": { sector: "Financials", subsector: "Transaction & Payment Processing Services" },
  "YSS": { sector: "Information Technology", subsector: "Software" },
  "YUM": { sector: "Consumer Discretionary", subsector: "Restaurants" },
  "ZBH": { sector: "Health Care", subsector: "Health Care Equipment" },
  "ZBRA": { sector: "Information Technology", subsector: "Electronic Equipment & Instruments" },
  "ZS": { sector: "Information Technology", subsector: "Cybersecurity" },
  "ZTS": { sector: "Health Care", subsector: "Pharmaceuticals" },

  "PALL": { sector: "Commodities", subsector: "Precious Metals" },
  "PPLT": { sector: "Commodities", subsector: "Precious Metals" },
  "GLD": { sector: "Commodities", subsector: "Precious Metals" },
  "SLV": { sector: "Commodities", subsector: "Precious Metals" },
  "SOXL": { sector: "Information Technology", subsector: "Leveraged ETF" },
  "SOXX": { sector: "Information Technology", subsector: "Semiconductor ETF" },
  "ITA": { sector: "Industrials", subsector: "Aerospace & Defense ETF" },
  "COPX": { sector: "Materials", subsector: "Copper Mining ETF" },
  "URA": { sector: "Energy", subsector: "Uranium ETF" },
  "AZN": { sector: "Health Care", subsector: "Biopharma" },
  "BMNR": { sector: "Digital Assets", subsector: "Crypto Mining" },
  "CRCL": { sector: "Digital Assets", subsector: "Crypto-Linked Equity" },
  "UUUU": { sector: "Energy", subsector: "Uranium Mining" },
  "MRVL": { sector: "Information Technology", subsector: "Semiconductors" },
  "PL": { sector: "Industrials", subsector: "Defense & Space" },
  "USAR": { sector: "Materials", subsector: "Metals & Mining" },

  "RCAT": { sector: "Industrials", subsector: "Defense & Space" },
  "SBET": { sector: "Communication Services", subsector: "Gambling" },
  "GDX": { sector: "Materials", subsector: "Gold Miners ETF" },
  "SMH": { sector: "Information Technology", subsector: "Semiconductor ETF" },
  "NLR": { sector: "Energy", subsector: "Uranium ETF" },

  // Trending / meme / extra-stock universe overrides
  "BWEN": { sector: "Industrials", subsector: "Wind Turbine Components" },
  "KEEL": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "LFVN": { sector: "Consumer Staples", subsector: "Health & Wellness" },
  "CC": { sector: "Materials", subsector: "Specialty Chemicals" },
  "JD": { sector: "Consumer Discretionary", subsector: "Internet Retail" },
  "BIRD": { sector: "Consumer Discretionary", subsector: "Footwear" },
  "FIG": { sector: "Information Technology", subsector: "Design Software" },
  "QURE": { sector: "Health Care", subsector: "Biotechnology" },
  "IQ": { sector: "Communication Services", subsector: "Streaming Media" },
  "YOU": { sector: "Industrials", subsector: "Security Services" },
  "PUMP": { sector: "Energy", subsector: "Oilfield Services" },
  "UP": { sector: "Industrials", subsector: "Aviation Services" },
  "BABA": { sector: "Consumer Discretionary", subsector: "Internet Retail" },
  "VC": { sector: "Consumer Discretionary", subsector: "Auto Parts" },
  "AGI": { sector: "Materials", subsector: "Gold Mining" },
  "API": { sector: "Information Technology", subsector: "Communications API" },
  "ICCM": { sector: "Health Care", subsector: "Biotechnology" },
  "SNBR": { sector: "Consumer Discretionary", subsector: "Home Furnishings" },
  "BRAI": { sector: "Information Technology", subsector: "AI Platform" },
  "FRMI": { sector: "Health Care", subsector: "Biotechnology" },
  "TE": { sector: "Information Technology", subsector: "Electronic Components" },
  "PDYN": { sector: "Health Care", subsector: "Biotechnology" },
  "LNAI": { sector: "Information Technology", subsector: "AI Platform" },
  "SPCX": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "GETY": { sector: "Communication Services", subsector: "Publishing" },
  "SLS": { sector: "Health Care", subsector: "Biotechnology" },
  "WYFI": { sector: "Communication Services", subsector: "Telecom Services" },
  "WTI": { sector: "Energy", subsector: "Oil & Gas E&P" },
  "FOR": { sector: "Real Estate", subsector: "Real Estate Development" },
  "PS": { sector: "Information Technology", subsector: "Application Software" },
  "NOK": { sector: "Information Technology", subsector: "Communications Equipment" },
  "GO": { sector: "Consumer Staples", subsector: "Grocery Stores" },
  "SONY": { sector: "Consumer Discretionary", subsector: "Consumer Electronics" },
  "RE": { sector: "Financials", subsector: "Reinsurance" },
  "WEN": { sector: "Consumer Discretionary", subsector: "Restaurants" },
  "CBRS": { sector: "Information Technology", subsector: "Semiconductors" },
  "OI": { sector: "Materials", subsector: "Paper & Plastic Packaging Products & Materials" },
  "PR": { sector: "Energy", subsector: "Oil & Gas Exploration & Production" },
  "OR": { sector: "Materials", subsector: "Gold Mining" },
  "BJ": { sector: "Consumer Staples", subsector: "Consumer Staples Merchandise Retail" },
  "OS": { sector: "Information Technology", subsector: "Application Software" },
  "RUN": { sector: "Utilities", subsector: "Independent Power Producers & Energy Traders" },
  "HTZ": { sector: "Industrials", subsector: "Rental & Leasing Services" },
  "PLSM": { sector: "Health Care", subsector: "Health Care Equipment" },
  "ABVX": { sector: "Health Care", subsector: "Biotechnology" },
  "CUPR": { sector: "Health Care", subsector: "Health Care Supplies" },
  "FRTT": { sector: "Consumer Discretionary", subsector: "Household Products" },
  "ADTX": { sector: "Health Care", subsector: "Biotechnology" },
  "ABSI": { sector: "Health Care", subsector: "Biotechnology" },
  "GPUS": { sector: "Information Technology", subsector: "Cloud Infrastructure" },
  "RKT": { sector: "Financials", subsector: "Consumer Finance" },
  "AIP": { sector: "Information Technology", subsector: "Semiconductors" },
  "AMBQ": { sector: "Information Technology", subsector: "Semiconductors" },
  "BAND": { sector: "Information Technology", subsector: "Systems Software" },
  "BE": { sector: "Industrials", subsector: "Electrical Components & Equipment" },
  "BRUM": { sector: "Information Technology", subsector: "Systems Software" },
  "BW": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "CRDO": { sector: "Information Technology", subsector: "Semiconductors" },
  "DGXN": { sector: "Utilities", subsector: "Independent Power Producers & Energy Traders" },
  "DOCN": { sector: "Information Technology", subsector: "Systems Software" },
  "ICHR": { sector: "Information Technology", subsector: "Semiconductor Materials & Equipment" },
  "LASE": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "PENG": { sector: "Information Technology", subsector: "IT Services" },
  "QTEX": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "QUCY": { sector: "Health Care", subsector: "Life Sciences Tools & Services" },
  "RGNT": { sector: "Health Care", subsector: "Health Care Supplies" },
  "SHAZ": { sector: "Information Technology", subsector: "IT Services" },
  "STI": { sector: "Industrials", subsector: "Electrical Components & Equipment" },
  "JACK": { sector: "Consumer Discretionary", subsector: "Restaurants" },
  "REAL": { sector: "Consumer Discretionary", subsector: "Apparel Retail" },
  "KUST": { sector: "Communication Services", subsector: "Movies & Entertainment" },
  "IQST": { sector: "Communication Services", subsector: "Telecom Services" },
  "WYY": { sector: "Information Technology", subsector: "IT Services" },
  "AZI": { sector: "Consumer Discretionary", subsector: "Auto Retail" },
  "MIMI": { sector: "Industrials", subsector: "Construction & Engineering" },
  "NEXR": { sector: "Consumer Discretionary", subsector: "Internet Retail" },
  "NNOX": { sector: "Health Care", subsector: "Health Care Equipment" },
  "WAVE": { sector: "Utilities", subsector: "Independent Power Producers & Energy Traders" },
  "GRPN": { sector: "Consumer Discretionary", subsector: "Broadline Retail" },
  "ANY": { sector: "Financials", subsector: "Capital Markets" },
  "ILLR": { sector: "Information Technology", subsector: "Application Software" },
  "INOD": { sector: "Industrials", subsector: "Research & Consulting Services" },
  "AYI": { sector: "Industrials", subsector: "Electrical Components & Equipment" },
  "MGNI": { sector: "Communication Services", subsector: "Advertising" },
  "JBLU": { sector: "Industrials", subsector: "Passenger Airlines" },
  "VSXY": { sector: "Consumer Discretionary", subsector: "Apparel Retail" },
  "KSS": { sector: "Consumer Discretionary", subsector: "Department Stores" },
  "TXG": { sector: "Health Care", subsector: "Life Sciences Tools & Services" },
  "OSCR": { sector: "Health Care", subsector: "Managed Health Care" },
  "NWL": { sector: "Consumer Staples", subsector: "Household Products" },
  "STUB": { sector: "Communication Services", subsector: "Interactive Media & Services" },
  "W": { sector: "Consumer Discretionary", subsector: "Internet Retail" },
  "ACHC": { sector: "Health Care", subsector: "Health Care Facilities" },
  "BFLY": { sector: "Health Care", subsector: "Health Care Equipment" },
  "WRBY": { sector: "Health Care", subsector: "Health Care Supplies" },
  "NESR": { sector: "Energy", subsector: "Oil & Gas Equipment & Services" },
  "PBF": { sector: "Energy", subsector: "Oil & Gas Refining & Marketing" },
  "COMP": { sector: "Real Estate", subsector: "Real Estate Services" },
  "ALGM": { sector: "Information Technology", subsector: "Semiconductors" },
  "MXL": { sector: "Information Technology", subsector: "Semiconductors" },
  "UMC": { sector: "Information Technology", subsector: "Semiconductors" },
  "APPS": { sector: "Information Technology", subsector: "Application Software" },
  "FROG": { sector: "Information Technology", subsector: "Application Software" },
  "NAVN": { sector: "Information Technology", subsector: "Application Software" },
  "QNT": { sector: "Information Technology", subsector: "Application Software" },
  "RELY": { sector: "Information Technology", subsector: "Systems Software" },
  "TENB": { sector: "Information Technology", subsector: "Systems Software" },
  "VRNS": { sector: "Information Technology", subsector: "Systems Software" },
  "INIO": { sector: "Industrials", subsector: "Industrial Machinery & Supplies & Components" },
  "RHI": { sector: "Industrials", subsector: "Human Resource & Employment Services" },
  "GLXY": { sector: "Financials", subsector: "Investment Banking & Brokerage" },
  "GNOM": { sector: "Health Care", subsector: "Thematic ETF" },
  "LAC": { sector: "Materials", subsector: "Metals & Mining" },
  "DC": { sector: "Materials", subsector: "Gold Mining" },
  "BULL": { sector: "Financials", subsector: "Investment Banking & Brokerage" },
  "EVER": { sector: "Communication Services", subsector: "Interactive Media & Services" },
  "SDOT": { sector: "Consumer Staples", subsector: "Agricultural Products & Services" },
  "IBRX": { sector: "Health Care", subsector: "Biotechnology" },
  "FUBO": { sector: "Communication Services", subsector: "Broadcasting" },
  "SOAR": { sector: "Industrials", subsector: "Aviation Services" },
  "VRDN": { sector: "Health Care", subsector: "Biotechnology" },
  "BATL": { sector: "Energy", subsector: "Oil & Gas Exploration & Production" },
  "TEM": { sector: "Health Care", subsector: "Health Care Technology" },
  "FORM": { sector: "Information Technology", subsector: "Semiconductor Materials & Equipment" },
  "SITM": { sector: "Information Technology", subsector: "Semiconductors" },
  "GDYN": { sector: "Information Technology", subsector: "IT Consulting & Other Services" },
  "SPSC": { sector: "Information Technology", subsector: "Application Software" },
  "VU": { sector: "Information Technology", subsector: "Electronic Components" },
  "SAAS": { sector: "Information Technology", subsector: "Application Software" },
  "NXQ": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "CHH": { sector: "Consumer Discretionary", subsector: "Household Products" },
  "045340": { sector: "Information Technology", subsector: "Application Software" },
  "SPR": { sector: "Information Technology", subsector: "IT Consulting & Other Services" },
  "7565": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "FCEL": { sector: "Industrials", subsector: "Electrical Components & Equipment" },
  "ATEX": { sector: "Communication Services", subsector: "Telecom Services" },
  "SDOT": { sector: "Consumer Staples", subsector: "Agricultural Products & Services" },
  "OUST": { sector: "Information Technology", subsector: "Electronic Components" },
  "APPS": { sector: "Information Technology", subsector: "Application Software" },
  "SLS": { sector: "Health Care", subsector: "Biotechnology" },
  "GVH": { sector: "Industrials", subsector: "Air Freight & Logistics" },
  "RGNX": { sector: "Health Care", subsector: "Biotechnology" },
  "BLZE": { sector: "Information Technology", subsector: "Systems Software" },
  "ABSI": { sector: "Health Care", subsector: "Biotechnology" },
  "BB": { sector: "Information Technology", subsector: "Systems Software" },
  "HQ": { sector: "Information Technology", subsector: "Systems Software" },
  "MEI": { sector: "Information Technology", subsector: "Electronic Components" },
  "DFTX": { sector: "Health Care", subsector: "Biotechnology" },
  "UPC": { sector: "Health Care", subsector: "Pharmaceuticals" },
  "PESI": { sector: "Industrials", subsector: "Environmental & Facilities Services" },
  "ODD": { sector: "Consumer Staples", subsector: "Household Products" },
  "JACK": { sector: "Consumer Discretionary", subsector: "Restaurants" },
  "NVCT": { sector: "Health Care", subsector: "Biotechnology" },
  "JDZG": { sector: "Consumer Discretionary", subsector: "Education Services" },
  "CUPR": { sector: "Health Care", subsector: "Health Care Supplies" },
  "SMWB": { sector: "Information Technology", subsector: "Application Software" },
  "AROQ": { sector: "Information Technology", subsector: "Systems Software" },
  "MBX": { sector: "Health Care", subsector: "Biotechnology" },
  "ZBI0": { sector: "Health Care", subsector: "Biotechnology" },
  "WSHP": { sector: "Communication Services", subsector: "Interactive Media & Services" },
  "EVC": { sector: "Communication Services", subsector: "Advertising" },
  "SEZL": { sector: "Financials", subsector: "Consumer Finance" },
  "AMPG": { sector: "Information Technology", subsector: "Communications Equipment" },
  "SLN": { sector: "Health Care", subsector: "Biotechnology" },
  "PRCH": { sector: "Financials", subsector: "Property & Casualty Insurance" },
  "BRBR": { sector: "Consumer Staples", subsector: "Packaged Foods & Meats" },
  "GRPN": { sector: "Communication Services", subsector: "Interactive Media & Services" },
  "ABVX": { sector: "Health Care", subsector: "Biotechnology" },
  "TENB": { sector: "Information Technology", subsector: "Systems Software" },
  "AXON": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "AMBA": { sector: "Information Technology", subsector: "Semiconductors" },
  "PRGS": { sector: "Information Technology", subsector: "Application Software" },
  "ELTX": { sector: "Health Care", subsector: "Biotechnology" },
  "NMAX": { sector: "Communication Services", subsector: "Broadcasting" },
  "RPD": { sector: "Information Technology", subsector: "Application Software" },
  "MNTN": { sector: "Information Technology", subsector: "Application Software" },
  "RXT": { sector: "Information Technology", subsector: "Systems Software" },
  "MXL": { sector: "Information Technology", subsector: "Semiconductors" },
  "PENG": { sector: "Information Technology", subsector: "IT Consulting & Other Services" },
  "BAND": { sector: "Information Technology", subsector: "Systems Software" },
  "ALAB": { sector: "Information Technology", subsector: "Semiconductors" },
  "VPG": { sector: "Information Technology", subsector: "Electronic Equipment & Instruments" },
  "SNDK": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "DELL": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "AMBQ": { sector: "Information Technology", subsector: "Semiconductors" },
  "ICHR": { sector: "Information Technology", subsector: "Semiconductor Materials & Equipment" },
  "CDNL": { sector: "Industrials", subsector: "Construction & Engineering" },
  "REPL": { sector: "Health Care", subsector: "Biotechnology" },
  "QURE": { sector: "Health Care", subsector: "Biotechnology" },
  "PSNL": { sector: "Health Care", subsector: "Health Care Services" },
  "ACMR": { sector: "Information Technology", subsector: "Semiconductor Materials & Equipment" },
  "QH": { sector: "Information Technology", subsector: "Application Software" },
  "QDEL": { sector: "Health Care", subsector: "Health Care Equipment" },
  "LILAK": { sector: "Communication Services", subsector: "Telecom Services" },
  "RGC": { sector: "Health Care", subsector: "Pharmaceuticals" },
  "ALIT": { sector: "Information Technology", subsector: "Application Software" },
  "AVAV": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "RDDT": { sector: "Communication Services", subsector: "Interactive Media & Services" },
  "FIGR": { sector: "Financials", subsector: "Capital Markets" },
  "UMAC": { sector: "Information Technology", subsector: "Technology Hardware, Storage & Peripherals" },
  "APP": { sector: "Communication Services", subsector: "Advertising" },
  "AEVA": { sector: "Information Technology", subsector: "Systems Software" },
  "AMPL": { sector: "Information Technology", subsector: "Application Software" },
  "BEAM": { sector: "Health Care", subsector: "Biotechnology" },
  "ABCL": { sector: "Health Care", subsector: "Biotechnology" },
  "WGS": { sector: "Health Care", subsector: "Biotechnology" },
  "NTLA": { sector: "Health Care", subsector: "Biotechnology" },
  "KRYS": { sector: "Health Care", subsector: "Biotechnology" },
  "TWST": { sector: "Health Care", subsector: "Biotechnology" },
  "DNA": { sector: "Health Care", subsector: "Biotechnology" },
  "IOVA": { sector: "Health Care", subsector: "Biotechnology" },
  "ILMN": { sector: "Health Care", subsector: "Biotechnology" },
  "EDIT": { sector: "Health Care", subsector: "Biotechnology" },
  "VCYT": { sector: "Health Care", subsector: "Biotechnology" },
  "ISSC": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "AIR": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "POWW": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "FLY": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "ECHO": { sector: "Communication Services", subsector: "Telecom Services" },
  "SPIR": { sector: "Industrials", subsector: "Specialty Business Services" },
  "VSAT": { sector: "Information Technology", subsector: "Communications Equipment" },
  "GSAT": { sector: "Communication Services", subsector: "Telecom Services" },
  "TSAT": { sector: "Information Technology", subsector: "Communications Equipment" },
  "BKSY": { sector: "Industrials", subsector: "Specialty Business Services" },
  "GAME": { sector: "Communication Services", subsector: "Interactive Media & Services" },
  "KRKNF": { sector: "Industrials", subsector: "Aerospace & Defense" },
  "MDA": { sector: "Industrials", subsector: "Defense & Space" },
  "EH": { sector: "Industrials", subsector: "Defense & Space" },
}
