export interface XStockProduct {
  tokenSymbol: string
  underlyingSymbol: string
  name: string
  tvTicker: string
}

const AMEX_ETFS = new Set([
  "BITX", "COPX", "DAX", "EWG", "EWQ", "EWU", "EWY", "FEZ", "GDX", "GLD",
  "IEMG", "IJR", "ITA", "IWM", "MOO", "NLR", "PALL", "PPLT", "QQQ", "SCHF",
  "SGOV", "SLV", "SMH", "SOXL", "SOXX", "SPY", "TQQQ", "URA", "VGK", "VOO",
  "VT", "VTI", "VUG", "VXUS", "XLE", "XOP",
])

const NASDAQ_SYMBOLS = new Set([
  "AAPL", "ADBE", "AMD", "AMAT", "AMBR", "ANET", "APLD", "APP", "ASML",
  "ASTS", "AVGO", "BTBT", "CEG", "CMCSA", "COIN", "CORZ", "CRCL", "CRWD",
  "CSCO", "CLSK", "DELL", "GOOGL", "HIMS", "HOOD", "HUT", "INTC", "IREN",
  "KLAC", "LRCX", "LITE", "MARA", "META", "MRVL", "MSFT", "MSTR", "MU",
  "NFLX", "NVDA", "OKLO", "ONDS", "OPEN", "ORCL", "PANW", "PEP", "PL",
  "PLTR", "PYPL", "RCAT", "RIOT", "RBLX", "SBET", "SNDK", "SMCI", "SMR",
  "TER", "TMUS", "TSLA", "TSM", "WBD", "WULF",
])

function tvTicker(symbol: string): string {
  if (AMEX_ETFS.has(symbol)) return `AMEX:${symbol}`
  if (NASDAQ_SYMBOLS.has(symbol)) return `NASDAQ:${symbol}`
  return `NYSE:${symbol}`
}

function product(tokenSymbol: string, underlyingSymbol: string, name: string): XStockProduct {
  return {
    tokenSymbol,
    underlyingSymbol,
    name,
    tvTicker: tvTicker(underlyingSymbol),
  }
}

export const XSTOCK_PRODUCTS: XStockProduct[] = [
  product("ABTx", "ABT", "Abbott xStock"),
  product("ABBVx", "ABBV", "AbbVie xStock"),
  product("PALLx", "PALL", "abrdn Physical Palladium Shares xStock"),
  product("PPLTx", "PPLT", "abrdn Physical Platinum Shares xStock"),
  product("ACNx", "ACN", "Accenture xStock"),
  product("ADBEx", "ADBE", "Adobe xStock"),
  product("GOOGLx", "GOOGL", "Alphabet xStock"),
  product("AMZNx", "AMZN", "Amazon xStock"),
  product("AMBRx", "AMBR", "Amber xStock"),
  product("AMDx", "AMD", "AMD xStock"),
  product("AAPLx", "AAPL", "Apple xStock"),
  product("APLDx", "APLD", "Applied Digital Corporation xStock"),
  product("AMATx", "AMAT", "Applied Materials, Inc. xStock"),
  product("APPx", "APP", "AppLovin xStock"),
  product("ANETx", "ANET", "Arista Networks, Inc. xStock"),
  product("ASMLx", "ASML", "ASML xStock"),
  product("ASTSx", "ASTS", "AST SpaceMobile xStock"),
  product("AZNx", "AZN", "AstraZeneca xStock"),
  product("BACx", "BAC", "Bank of America xStock"),
  product("BRK.Bx", "BRK.B", "Berkshire Hathaway xStock"),
  product("BTBTx", "BTBT", "Bit Digital xStock"),
  product("BTGOx", "BTGO", "Bitgo xStock"),
  product("BMNRx", "BMNR", "Bitmine xStock"),
  product("AVGOx", "AVGO", "Broadcom xStock"),
  product("LNGx", "LNG", "Cheniere Energy xStock"),
  product("CVXx", "CVX", "Chevron xStock"),
  product("CRCLx", "CRCL", "Circle xStock"),
  product("CSCOx", "CSCO", "Cisco xStock"),
  product("CLSKx", "CLSK", "CleanSpark xStock"),
  product("NETx", "NET", "Cloudflare xStock"),
  product("KOx", "KO", "Coca-Cola xStock"),
  product("COINx", "COIN", "Coinbase xStock"),
  product("CMCSAx", "CMCSA", "Comcast xStock"),
  product("CEGx", "CEG", "Constellation Energy Corporation xStock"),
  product("IEMGx", "IEMG", "Core MSCI Emerging Markets xStock"),
  product("CORZx", "CORZ", "Core Scientific xStock"),
  product("CRWDx", "CRWD", "CrowdStrike xStock"),
  product("DHRx", "DHR", "Danaher xStock"),
  product("DELLx", "DELL", "Dell Technologies Inc. xStock"),
  product("SOXLx", "SOXL", "Direxion Semiconductor Bull 3X xStock"),
  product("ETNx", "ETN", "Eaton Corporation plc xStock"),
  product("LLYx", "LLY", "Eli Lilly xStock"),
  product("UUUUx", "UUUU", "Energy Fuels Inc. xStock"),
  product("XLEx", "XLE", "Energy Select Sector SPDR Fund xStock"),
  product("XOMx", "XOM", "Exxon Mobil xStock"),
  product("USPXx", "USPX", "Franklin U.S. Equity Index xStock"),
  product("FLQMx", "FLQM", "Franklin U.S. Mid Cap Multi-Factor xStock"),
  product("GMEx", "GME", "Gamestop xStock"),
  product("GEVx", "GEV", "GE Vernova Inc. xStock"),
  product("COPXx", "COPX", "Global X Copper Miners xStock"),
  product("DAXx", "DAX", "Global X DAX Germany xStock"),
  product("URAx", "URA", "Global X Uranium ETF xStock"),
  product("GLDx", "GLD", "Gold xStock"),
  product("GSx", "GS", "Goldman Sachs xStock"),
  product("HIMSx", "HIMS", "Hims & Hers xStock"),
  product("HDx", "HD", "Home Depot xStock"),
  product("HONx", "HON", "Honeywell xStock"),
  product("HUTx", "HUT", "Hut 8 xStock"),
  product("INTCx", "INTC", "Intel xStock"),
  product("IBMx", "IBM", "International Business Machines xStock"),
  product("IRENx", "IREN", "IREN xStock"),
  product("SGOVx", "SGOV", "iShares 0-3 Month Treasury Bond ETF xStock"),
  product("EWQx", "EWQ", "iShares MSCI France xStock"),
  product("EWGx", "EWG", "iShares MSCI Germany xStock"),
  product("EWYx", "EWY", "iShares MSCI South Korea xStock"),
  product("EWUx", "EWU", "iShares MSCI United Kingdom xStock"),
  product("SOXXx", "SOXX", "iShares Semiconductor xStock"),
  product("SLVx", "SLV", "iShares Silver Trust xStock"),
  product("ITAx", "ITA", "iShares U.S. Aerospace & Defense ETF xStock"),
  product("JNJx", "JNJ", "Johnson & Johnson xStock"),
  product("JPMx", "JPM", "JPMorgan Chase xStock"),
  product("JPSTx", "JPST", "JPMorgan Ultra-Short Income xStock"),
  product("KLACx", "KLAC", "KLA Corporation xStock"),
  product("LRCXx", "LRCX", "Lam Research Corporation xStock"),
  product("LINx", "LIN", "Linde xStock"),
  product("LITEx", "LITE", "Lumentum Holdings Inc. xStock"),
  product("MARAx", "MARA", "MARA xStock"),
  product("MRVLx", "MRVL", "Marvell xStock"),
  product("MAx", "MA", "Mastercard xStock"),
  product("MCDx", "MCD", "McDonald's xStock"),
  product("MDTx", "MDT", "Medtronic xStock"),
  product("MRKx", "MRK", "Merck xStock"),
  product("METAx", "META", "Meta xStock"),
  product("MUx", "MU", "Micron Technology xStock"),
  product("MSFTx", "MSFT", "Microsoft xStock"),
  product("MSTRx", "MSTR", "MicroStrategy xStock"),
  product("QQQx", "QQQ", "Nasdaq xStock"),
  product("NFLXx", "NFLX", "Netflix xStock"),
  product("NVOx", "NVO", "Novo Nordisk xStock"),
  product("SMRx", "SMR", "NuScale Power Corporation xStock"),
  product("NVDAx", "NVDA", "NVIDIA xStock"),
  product("OKLOx", "OKLO", "Oklo xStock"),
  product("ONDSx", "ONDS", "Ondas xStock"),
  product("OPENx", "OPEN", "OPEN xStock"),
  product("ORCLx", "ORCL", "Oracle xStock"),
  product("PLTRx", "PLTR", "Palantir xStock"),
  product("PANWx", "PANW", "Palo Alto Networks xStock"),
  product("PYPLx", "PYPL", "PayPal xStock"),
  product("PEPx", "PEP", "PepsiCo xStock"),
  product("PFEx", "PFE", "Pfizer xStock"),
  product("PMx", "PM", "Philip Morris xStock"),
  product("PLx", "PL", "Planet Labs xStock"),
  product("PGx", "PG", "Procter & Gamble xStock"),
  product("PWRx", "PWR", "Quanta Services, Inc. xStock"),
  product("RCATx", "RCAT", "Red Cat xStock"),
  product("RIOTx", "RIOT", "Riot Platforms xStock"),
  product("HOODx", "HOOD", "Robinhood xStock"),
  product("RBLXx", "RBLX", "Roblox xStock"),
  product("IWMx", "IWM", "Russell 2000 xStock"),
  product("IJRx", "IJR", "S&P Small Cap xStock"),
  product("CRMx", "CRM", "Salesforce xStock"),
  product("SNDKx", "SNDK", "Sandisk Corporation xStock"),
  product("SCHFx", "SCHF", "Schwab International Equity xStock"),
  product("SBETx", "SBET", "SharpLink Gaming xStock"),
  product("SPYx", "SPY", "SP500 xStock"),
  product("FEZx", "FEZ", "SPDR EURO STOXX 50 xStock"),
  product("XOPx", "XOP", "SPDR S&P Oil & Gas Exploration & Production ETF xStock"),
  product("SMCIx", "SMCI", "Super Micro Computer, Inc. xStock"),
  product("TMUSx", "TMUS", "T-Mobile xStock"),
  product("TERx", "TER", "Teradyne, Inc. xStock"),
  product("WULFx", "WULF", "TeraWulf xStock"),
  product("TSLAx", "TSLA", "Tesla xStock"),
  product("TMOx", "TMO", "Thermo Fisher xStock"),
  product("TQQQx", "TQQQ", "TQQQ xStock"),
  product("TSMx", "TSM", "TSMC xStock"),
  product("UBERx", "UBER", "Uber xStock"),
  product("UNHx", "UNH", "UnitedHealth xStock"),
  product("USARx", "USAR", "USA Rare Earth Inc. xStock"),
  product("MOOx", "MOO", "VanEck Agribusiness ETF xStock"),
  product("GDXx", "GDX", "VanEck Gold Miners xStock"),
  product("SMHx", "SMH", "VanEck Semiconductor ETF xStock"),
  product("NLRx", "NLR", "VanEck Uranium and Nuclear xStock"),
  product("VGKx", "VGK", "Vanguard FTSE Europe ETF xStock"),
  product("VUGx", "VUG", "Vanguard Growth ETF xStock"),
  product("VOOx", "VOO", "Vanguard S&P 500 xStock"),
  product("VXUSx", "VXUS", "Vanguard Total International Stock ETF xStock"),
  product("VTx", "VT", "Vanguard Total World xStock"),
  product("VTIx", "VTI", "Vanguard xStock"),
  product("VRTx", "VRT", "Vertiv Holdings Co xStock"),
  product("SPCEx", "SPCE", "Virgin Galactic xStock"),
  product("Vx", "V", "Visa xStock"),
  product("BITXx", "BITX", "Volatility Shares 2x Bitcoin Strategy xStock"),
  product("WMTx", "WMT", "Walmart xStock"),
  product("WBDx", "WBD", "Warner Bros. Discovery xStock"),
]
