services:
  - type: web
    name: breakingout
    runtime: node
    repo: https://github.com/tuxcanfly/breakingout.xyz
    branch: master
    rootDir: dashboard
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/dashboard
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: node_modules/.cache/puppeteer
